title: GA4GH Operations and Communications
description: Resources, updates, and actions for active GA4GH contributors.
show_downloads: false
theme: jekyll-theme-cayman
github:
  index_url: https://ajhpage.github.io/ga4gh-ops.github.io//index.md
  newsletters_url: https://ajhpage.github.io/ga4gh-ops.github.io//newsletters.md
  meetings_url: https://ajhpage.github.io/ga4gh-ops.github.io//meetings.md
  resources_url: https://ajhpage.github.io/ga4gh-ops.github.io//resources.md
