title: GA4GH::ops
logo: [<img src="https://www.ga4gh.org/wp-content/themes/ga4gh-theme/gfx/GA-logo-horizontal-tag-RGB.svg">](https://www.ga4gh.org/)
description: Resources, actions, and updates for active GA4GH contributors.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
